/*

 AI_BLANK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 7
   Map size      : 20 x 18
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __ai_blank_h_INCLUDE
#define __ai_blank_h_INCLUDE

#define ai_blankWidth 20
#define ai_blankHeight 18
#define ai_blankBank 7

#define ai_blank ai_blankPLN0
extern const unsigned char ai_blankPLN0[];
extern const unsigned char ai_blankPLN1[];

#endif

/* End of AI_BLANK.H */
