/*

 AI_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 7
   Map size      : 20 x 18
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __ai_map_h_INCLUDE
#define __ai_map_h_INCLUDE

#define ai_mapWidth 20
#define ai_mapHeight 18
#define ai_mapBank 7

#define ai_map ai_mapPLN0
extern const unsigned char ai_mapPLN0[];
extern const unsigned char ai_mapPLN1[];

#endif

/* End of AI_MAP.H */
