/*

 ALPHA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 51

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __alpha_h_INCLUDE
#define __alpha_h_INCLUDE

/* Bank of tiles. */
#define AlphaBank 4
/* Start of tile array. */
extern const void __bank_Alpha;
extern const unsigned char Alpha[];

#endif

/* End of ALPHA.H */
