/*

 BEAM2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 32 x 32
   Tile set      : sokoban_bg3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __beam2_h_INCLUDE
#define __beam2_h_INCLUDE

#define Beam2Width 32
#define Beam2Height 32
#define Beam2Bank 1

#define Beam2 Beam2PLN0
extern const unsigned char Beam2PLN0[];
extern const unsigned char Beam2PLN1[];

#endif

/* End of BEAM2.H */
