/*

 BG_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __bg_tiles_h_INCLUDE
#define __bg_tiles_h_INCLUDE

/* Bank of tiles. */
#define BGTilesBank 1

/* Super Gameboy palette 0 */
#define BGTilesSGBPal0c0 6076
#define BGTilesSGBPal0c1 8935
#define BGTilesSGBPal0c2 6596
#define BGTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BGTilesSGBPal1c0 6076
#define BGTilesSGBPal1c1 8935
#define BGTilesSGBPal1c2 6596
#define BGTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BGTilesSGBPal2c0 6076
#define BGTilesSGBPal2c1 8935
#define BGTilesSGBPal2c2 6596
#define BGTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BGTilesSGBPal3c0 6076
#define BGTilesSGBPal3c1 8935
#define BGTilesSGBPal3c2 6596
#define BGTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BGTilesCGBPal0c0 25147
#define BGTilesCGBPal0c1 18741
#define BGTilesCGBPal0c2 9260
#define BGTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define BGTilesCGBPal1c0 21010
#define BGTilesCGBPal1c1 16782
#define BGTilesCGBPal1c2 11497
#define BGTilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define BGTilesCGBPal2c0 32767
#define BGTilesCGBPal2c1 25368
#define BGTilesCGBPal2c2 16912
#define BGTilesCGBPal2c3 8456

/* Gameboy Color palette 3 */
#define BGTilesCGBPal3c0 32767
#define BGTilesCGBPal3c1 25368
#define BGTilesCGBPal3c2 16912
#define BGTilesCGBPal3c3 8456

/* Gameboy Color palette 4 */
#define BGTilesCGBPal4c0 32767
#define BGTilesCGBPal4c1 25368
#define BGTilesCGBPal4c2 16912
#define BGTilesCGBPal4c3 8456

/* Gameboy Color palette 5 */
#define BGTilesCGBPal5c0 32767
#define BGTilesCGBPal5c1 23510
#define BGTilesCGBPal5c2 12192
#define BGTilesCGBPal5c3 1632

/* Gameboy Color palette 6 */
#define BGTilesCGBPal6c0 31643
#define BGTilesCGBPal6c1 32427
#define BGTilesCGBPal6c2 25888
#define BGTilesCGBPal6c3 10274

/* Gameboy Color palette 7 */
#define BGTilesCGBPal7c0 9727
#define BGTilesCGBPal7c1 10207
#define BGTilesCGBPal7c2 2143
#define BGTilesCGBPal7c3 1066
/* Start of tile array. */
extern const void __bank_BGTiles;
extern const unsigned char BGTiles[];

#endif

/* End of BG_TILES.H */
