/*

 BLANK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 18 x 20
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __blank_h_INCLUDE
#define __blank_h_INCLUDE

#define BlankBlackWidth 18
#define BlankBlackHeight 20
#define BlankBlackBank 4

#define BlankBlack BlankBlackPLN0
extern const unsigned char BlankBlackPLN0[];

#endif

/* End of BLANK.H */
