/*

 BLOBS2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 20 x 18
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __blobs2_h_INCLUDE
#define __blobs2_h_INCLUDE

#define Blobs2Width 20
#define Blobs2Height 18
#define Blobs2Bank 4

#define Blobs2 Blobs2PLN0
extern const unsigned char Blobs2PLN0[];
extern const unsigned char Blobs2PLN1[];

#endif

/* End of BLOBS2.H */
