/*

 BLOBS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 20 x 18
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __blobs_h_INCLUDE
#define __blobs_h_INCLUDE

#define BlobsWidth 20
#define BlobsHeight 18
#define BlobsBank 4

#define Blobs BlobsPLN0
extern const unsigned char BlobsPLN0[];
extern const unsigned char BlobsPLN1[];

#endif

/* End of BLOBS.H */
