/*

 BLOCKED.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 32 x 32
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __blocked_h_INCLUDE
#define __blocked_h_INCLUDE

#define BlockedWidth 32
#define BlockedHeight 32
#define BlockedBank 3

#define Blocked BlockedPLN0
extern const unsigned char BlockedPLN0[];
extern const unsigned char BlockedPLN1[];

#endif

/* End of BLOCKED.H */
