/*

 BOOT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 5
   Map size      : 20 x 18
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __boot_h_INCLUDE
#define __boot_h_INCLUDE

#define BootWidth 20
#define BootHeight 18
#define BootBank 5

#define Boot BootPLN0
extern const unsigned char BootPLN0[];

#endif

/* End of BOOT.H */
