/*

 CHASM.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 32 x 32
   Tile set      : sokoban_bg3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __chasm_h_INCLUDE
#define __chasm_h_INCLUDE

#define ChasmWidth 32
#define ChasmHeight 32
#define ChasmBank 1

#define Chasm ChasmPLN0
extern const unsigned char ChasmPLN0[];
extern const unsigned char ChasmPLN1[];

#endif

/* End of CHASM.H */
