/*

 CIRCLES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 39

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __circles_h_INCLUDE
#define __circles_h_INCLUDE

/* Bank of tiles. */
#define CirclesBank 0

/* Super Gameboy palette 0 */
#define CirclesSGBPal0c0 6076
#define CirclesSGBPal0c1 8935
#define CirclesSGBPal0c2 6596
#define CirclesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define CirclesSGBPal1c0 6076
#define CirclesSGBPal1c1 8935
#define CirclesSGBPal1c2 6596
#define CirclesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define CirclesSGBPal2c0 6076
#define CirclesSGBPal2c1 8935
#define CirclesSGBPal2c2 6596
#define CirclesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define CirclesSGBPal3c0 6076
#define CirclesSGBPal3c1 8935
#define CirclesSGBPal3c2 6596
#define CirclesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define CirclesCGBPal0c0 6076
#define CirclesCGBPal0c1 8935
#define CirclesCGBPal0c2 6596
#define CirclesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define CirclesCGBPal1c0 6076
#define CirclesCGBPal1c1 8935
#define CirclesCGBPal1c2 6596
#define CirclesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define CirclesCGBPal2c0 6076
#define CirclesCGBPal2c1 8935
#define CirclesCGBPal2c2 6596
#define CirclesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define CirclesCGBPal3c0 6076
#define CirclesCGBPal3c1 8935
#define CirclesCGBPal3c2 6596
#define CirclesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define CirclesCGBPal4c0 6076
#define CirclesCGBPal4c1 8935
#define CirclesCGBPal4c2 6596
#define CirclesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define CirclesCGBPal5c0 6076
#define CirclesCGBPal5c1 8935
#define CirclesCGBPal5c2 6596
#define CirclesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define CirclesCGBPal6c0 6076
#define CirclesCGBPal6c1 8935
#define CirclesCGBPal6c2 6596
#define CirclesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define CirclesCGBPal7c0 6076
#define CirclesCGBPal7c1 8935
#define CirclesCGBPal7c2 6596
#define CirclesCGBPal7c3 5344

/* CGB palette entries. */
#define CirclesCGB0 0
#define CirclesCGB1 0
#define CirclesCGB2 0
#define CirclesCGB3 0
#define CirclesCGB4 0
#define CirclesCGB5 0
#define CirclesCGB6 0
#define CirclesCGB7 0
#define CirclesCGB8 0
#define CirclesCGB9 0
#define CirclesCGB10 0
#define CirclesCGB11 0
#define CirclesCGB12 0
#define CirclesCGB13 0
#define CirclesCGB14 0
#define CirclesCGB15 0
#define CirclesCGB16 0
#define CirclesCGB17 0
#define CirclesCGB18 0
#define CirclesCGB19 0
#define CirclesCGB20 0
#define CirclesCGB21 0
#define CirclesCGB22 0
#define CirclesCGB23 0
#define CirclesCGB24 0
#define CirclesCGB25 0
#define CirclesCGB26 0
#define CirclesCGB27 0
#define CirclesCGB28 0
#define CirclesCGB29 0
#define CirclesCGB30 0
#define CirclesCGB31 0
#define CirclesCGB32 0
#define CirclesCGB33 0
#define CirclesCGB34 0
#define CirclesCGB35 0
#define CirclesCGB36 0
#define CirclesCGB37 0
#define CirclesCGB38 0
#define CirclesCGB39 0
/* Start of tile array. */
extern const unsigned char Circles[];

#endif

/* End of CIRCLES.H */
