/*

 CONTINUE_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 22

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __continue_tiles_h_INCLUDE
#define __continue_tiles_h_INCLUDE

/* Bank of tiles. */
#define ContinueTilesBank 7
/* Start of tile array. */
extern const void __bank_ContinueTiles;
extern const unsigned char ContinueTiles[];

#endif

/* End of CONTINUE_TILES.H */
