/*

 DECAY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 32 x 32
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __decay_h_INCLUDE
#define __decay_h_INCLUDE

#define DecayWidth 32
#define DecayHeight 32
#define DecayBank 3

#define Decay DecayPLN0
extern const unsigned char DecayPLN0[];
extern const unsigned char DecayPLN1[];

#endif

/* End of DECAY.H */
