/*

 EASY2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 32 x 32
   Tile set      : sokoban_bg3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __easy2_h_INCLUDE
#define __easy2_h_INCLUDE

#define Easy2Width 32
#define Easy2Height 32
#define Easy2Bank 1

#define Easy2 Easy2PLN0
extern const unsigned char Easy2PLN0[];
extern const unsigned char Easy2PLN1[];

#endif

/* End of EASY2.H */
