/*

 EASY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 32 x 32
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __easy_h_INCLUDE
#define __easy_h_INCLUDE

#define EasyWidth 32
#define EasyHeight 32
#define EasyBank 3

#define Easy EasyPLN0
extern const unsigned char EasyPLN0[];
extern const unsigned char EasyPLN1[];

#endif

/* End of EASY.H */
