/*

 ENTRY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 32 x 32
   Tile set      : sokoban_bg3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __entry_h_INCLUDE
#define __entry_h_INCLUDE

#define EntryWidth 32
#define EntryHeight 32
#define EntryBank 1

#define Entry EntryPLN0
extern const unsigned char EntryPLN0[];
extern const unsigned char EntryPLN1[];

#endif

/* End of ENTRY.H */
