//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_face_H
#define METASPRITE_face_H

#include <stdint.h>

#define face_TILE_H 8
#define face_WIDTH 160
#define face_HEIGHT 144
#define face_MAP_ATTRIBUTES 0
#define face_TILE_PALS face_tile_pals


extern const uint16_t face_palettes[4];
extern const uint8_t face_tiles[2608];

extern const unsigned char face_map[360];
extern const unsigned char* face_tile_pals[163];

#endif
