/*

 FRAME_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 5
   Map size      : 20 x 5
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 210
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __frame_map_h_INCLUDE
#define __frame_map_h_INCLUDE

#define FrameMapWidth 20
#define FrameMapHeight 5
#define FrameMapBank 5

#define FrameMap FrameMapPLN0
extern const unsigned char FrameMapPLN0[];

#endif

/* End of FRAME_MAP.H */
