/*

 FRAME_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __frame_tiles_h_INCLUDE
#define __frame_tiles_h_INCLUDE

/* Bank of tiles. */
#define FrameBank 5
/* Start of tile array. */
extern const void __bank_Frame;
extern const unsigned char Frame[];

#endif

/* End of FRAME_TILES.H */
