/*

 INTRO_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 20 x 28
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __intro_map_h_INCLUDE
#define __intro_map_h_INCLUDE

#define IntroMapWidth 20
#define IntroMapHeight 28
#define IntroMapBank 4

#define IntroMap IntroMapPLN0
extern const unsigned char IntroMapPLN0[];

#endif

/* End of INTRO_MAP.H */
