//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_karen1_H
#define METASPRITE_karen1_H

#include <stdint.h>


extern const uint16_t karen1_palettes[4];
extern const uint8_t karen1_tiles[2640];

extern const unsigned char karen1_map[360];
extern const unsigned char* karen1_tile_pals[165];

#endif
