/*

 LOGO_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __logo_tiles_h_INCLUDE
#define __logo_tiles_h_INCLUDE

/* Bank of tiles. */
#define LogoTilesBank 4
/* Start of tile array. */
extern const void __bank_LogoTiles;
extern const unsigned char LogoTiles[];

#endif

/* End of LOGO_TILES.H */
