/*

 MEETING.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 32 x 32
   Tile set      : sokoban_bg3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __meeting_h_INCLUDE
#define __meeting_h_INCLUDE

#define MeetingWidth 32
#define MeetingHeight 32
#define MeetingBank 3

#define Meeting MeetingPLN0
extern const unsigned char MeetingPLN0[];
extern const unsigned char MeetingPLN1[];

#endif

/* End of MEETING.H */
