/*

 NOWALL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 32 x 32
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __nowall_h_INCLUDE
#define __nowall_h_INCLUDE

#define NoWallWidth 32
#define NoWallHeight 32
#define NoWallBank 3

#define NoWall NoWallPLN0
extern const unsigned char NoWallPLN0[];
extern const unsigned char NoWallPLN1[];

#endif

/* End of NOWALL.H */
