/*

 PILLARS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 32 x 32
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __pillars_h_INCLUDE
#define __pillars_h_INCLUDE

#define PillarsWidth 32
#define PillarsHeight 32
#define PillarsBank 3

#define Pillars PillarsPLN0
extern const unsigned char PillarsPLN0[];
extern const unsigned char PillarsPLN1[];

#endif

/* End of PILLARS.H */
