/*

 PLANE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 14 x 21
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __plane_h_INCLUDE
#define __plane_h_INCLUDE

#define PlaneWidth 14
#define PlaneHeight 21
#define PlaneBank 4

extern const unsigned char Plane[];

#endif

/* End of PLANE.H */
