/*

 PRETEXT_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 20 x 3
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __pretext_map_h_INCLUDE
#define __pretext_map_h_INCLUDE

#define PretextMapWidth 20
#define PretextMapHeight 3
#define PretextMapBank 4

#define PretextMap PretextMapPLN0
extern const unsigned char PretextMapPLN0[];

#endif

/* End of PRETEXT_MAP.H */
