//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_profd_H
#define METASPRITE_profd_H

#include <stdint.h>

extern const uint16_t profd_palettes[4];
extern const uint8_t profd_tiles[2048];

extern const unsigned char profd_map[360];
extern const unsigned char* profd_tile_pals[128];

#endif
