/*

 REENTRY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 32 x 32
   Tile set      : sokoban_bg3.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __reentry_h_INCLUDE
#define __reentry_h_INCLUDE

#define ReentryWidth 32
#define ReentryHeight 32
#define ReentryBank 3

#define Reentry ReentryPLN0
extern const unsigned char ReentryPLN0[];
extern const unsigned char ReentryPLN1[];

#endif

/* End of REENTRY.H */
