/*

 ROOMS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 32 x 32
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __rooms_h_INCLUDE
#define __rooms_h_INCLUDE

#define RoomsWidth 32
#define RoomsHeight 32
#define RoomsBank 3

#define Rooms RoomsPLN0
extern const unsigned char RoomsPLN0[];
extern const unsigned char RoomsPLN1[];

#endif

/* End of ROOMS.H */
