/*

 SOKOBAN_SPRITE_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 300

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __sokoban_sprite_tiles_h_INCLUDE
#define __sokoban_sprite_tiles_h_INCLUDE

/* Bank of tiles. */
#define spritesBank 0

/* Gameboy Color palette 0 */
#define spritesCGBPal0c0 0
#define spritesCGBPal0c1 0x36de
#define spritesCGBPal0c2 0x013c
#define spritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define spritesCGBPal1c0 0
#define spritesCGBPal1c1 0x7bde
#define spritesCGBPal1c2 0x03de
#define spritesCGBPal1c3 0x2c0a

/* Gameboy Color palette 2 */
#define spritesCGBPal2c0 32767
#define spritesCGBPal2c1 8935
#define spritesCGBPal2c2 0x2168
#define spritesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define spritesCGBPal3c0 32767
#define spritesCGBPal3c1 8935
#define spritesCGBPal3c2 6596
#define spritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define spritesCGBPal4c0 32767
#define spritesCGBPal4c1 8935
#define spritesCGBPal4c2 6596
#define spritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define spritesCGBPal5c0 32767
#define spritesCGBPal5c1 27550
#define spritesCGBPal5c2 700
#define spritesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define spritesCGBPal6c0 32767
#define spritesCGBPal6c1 25023
#define spritesCGBPal6c2 7196
#define spritesCGBPal6c3 6186

/* Gameboy Color palette 7 */
#define spritesCGBPal7c0 6076
#define spritesCGBPal7c1 10207
#define spritesCGBPal7c2 2143
#define spritesCGBPal7c3 1066

/* Start of tile array. */
extern const unsigned char sprites[];

#endif

/* End of SOKOBAN_SPRITE_TILES.H */
