/*

 TRIANGLES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 27

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __triangles_h_INCLUDE
#define __triangles_h_INCLUDE

/* Bank of tiles. */

/* Super Gameboy palette 0 */
#define TrianglesSGBPal0c0 6076
#define TrianglesSGBPal0c1 8935
#define TrianglesSGBPal0c2 6596
#define TrianglesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TrianglesSGBPal1c0 6076
#define TrianglesSGBPal1c1 8935
#define TrianglesSGBPal1c2 6596
#define TrianglesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TrianglesSGBPal2c0 6076
#define TrianglesSGBPal2c1 8935
#define TrianglesSGBPal2c2 6596
#define TrianglesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TrianglesSGBPal3c0 6076
#define TrianglesSGBPal3c1 8935
#define TrianglesSGBPal3c2 6596
#define TrianglesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TrianglesCGBPal0c0 21930
#define TrianglesCGBPal0c1 16580
#define TrianglesCGBPal0c2 13312
#define TrianglesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define TrianglesCGBPal1c0 9752
#define TrianglesCGBPal1c1 341
#define TrianglesCGBPal1c2 5330
#define TrianglesCGBPal1c3 5261

/* Gameboy Color palette 2 */
#define TrianglesCGBPal2c0 25566
#define TrianglesCGBPal2c1 14111
#define TrianglesCGBPal2c2 700
#define TrianglesCGBPal2c3 1293

/* Gameboy Color palette 3 */
#define TrianglesCGBPal3c0 31710
#define TrianglesCGBPal3c1 13741
#define TrianglesCGBPal3c2 8456
#define TrianglesCGBPal3c3 1057

/* Gameboy Color palette 4 */
#define TrianglesCGBPal4c0 21930
#define TrianglesCGBPal4c1 16580
#define TrianglesCGBPal4c2 8456
#define TrianglesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define TrianglesCGBPal5c0 9752
#define TrianglesCGBPal5c1 341
#define TrianglesCGBPal5c2 700
#define TrianglesCGBPal5c3 1293

/* Gameboy Color palette 6 */
#define TrianglesCGBPal6c0 25566
#define TrianglesCGBPal6c1 14111
#define TrianglesCGBPal6c2 700
#define TrianglesCGBPal6c3 1293

/* Gameboy Color palette 7 */
#define TrianglesCGBPal7c0 25566
#define TrianglesCGBPal7c1 13741
#define TrianglesCGBPal7c2 700
#define TrianglesCGBPal7c3 1057

/* CGB palette entries. */
#define TrianglesCGB0 0
#define TrianglesCGB1 0
#define TrianglesCGB2 0
#define TrianglesCGB3 0
#define TrianglesCGB4 0
#define TrianglesCGB5 0
#define TrianglesCGB6 0
#define TrianglesCGB7 0
#define TrianglesCGB8 0
#define TrianglesCGB9 0
#define TrianglesCGB10 0
#define TrianglesCGB11 0
#define TrianglesCGB12 0
#define TrianglesCGB13 0
#define TrianglesCGB14 0
#define TrianglesCGB15 0
#define TrianglesCGB16 0
#define TrianglesCGB17 0
#define TrianglesCGB18 0
#define TrianglesCGB19 0
#define TrianglesCGB20 0
#define TrianglesCGB21 0
#define TrianglesCGB22 0
#define TrianglesCGB23 0
#define TrianglesCGB24 0
#define TrianglesCGB25 0
#define TrianglesCGB26 0
#define TrianglesCGB27 0
/* Start of tile array. */
extern const unsigned char Triangles[];

#endif

/* End of TRIANGLES.H */
